"""crear tablas iniciales

Revision ID: 096705cc8648
Revises: 
Create Date: 2026-02-17 22:45:22.514104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '096705cc8648'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categoria',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_index(op.f('ix_categoria_id'), 'categoria', ['id'], unique=False)
    op.create_table('estado',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_index(op.f('ix_estado_id'), 'estado', ['id'], unique=False)
    op.create_table('navegador',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_navegador_id'), 'navegador', ['id'], unique=False)
    op.create_table('rol',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_index(op.f('ix_rol_id'), 'rol', ['id'], unique=False)
    op.create_table('usuario',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('contra_hash', sa.String(), nullable=True),
    sa.Column('rol_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['rol_id'], ['rol.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_usuario_id'), 'usuario', ['id'], unique=False)
    op.create_table('acceso',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('usuario_id', sa.UUID(), nullable=True),
    sa.Column('estado_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['estado_id'], ['estado.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_acceso_id'), 'acceso', ['id'], unique=False)
    op.create_table('egreso',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('descripcion', sa.String(), nullable=True),
    sa.Column('monto', sa.Double(), nullable=True),
    sa.Column('usuario_id', sa.UUID(), nullable=True),
    sa.Column('categoria_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['categoria_id'], ['categoria.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_egreso_id'), 'egreso', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_egreso_id'), table_name='egreso')
    op.drop_table('egreso')
    op.drop_index(op.f('ix_acceso_id'), table_name='acceso')
    op.drop_table('acceso')
    op.drop_index(op.f('ix_usuario_id'), table_name='usuario')
    op.drop_table('usuario')
    op.drop_index(op.f('ix_rol_id'), table_name='rol')
    op.drop_table('rol')
    op.drop_index(op.f('ix_navegador_id'), table_name='navegador')
    op.drop_table('navegador')
    op.drop_index(op.f('ix_estado_id'), table_name='estado')
    op.drop_table('estado')
    op.drop_index(op.f('ix_categoria_id'), table_name='categoria')
    op.drop_table('categoria')
    # ### end Alembic commands ###
