"""Quitar tabla navegador y agregarlo como atributo de acceso

Revision ID: 1228a37d2a13
Revises: 096705cc8648
Create Date: 2026-02-18 10:42:39.293524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1228a37d2a13'
down_revision: Union[str, Sequence[str], None] = '096705cc8648'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_navegador_id'), table_name='navegador')
    op.drop_table('navegador')
    op.add_column('acceso', sa.Column('navegador', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('acceso', 'navegador')
    op.create_table('navegador',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('nombre', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('navegador_pkey'))
    )
    op.create_index(op.f('ix_navegador_id'), 'navegador', ['id'], unique=False)
    # ### end Alembic commands ###
