"""auditoria accesos ip navegador token

Revision ID: 56ee731c264d
Revises: 096705cc8648
Create Date: 2026-02-18 09:59:00.177010

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56ee731c264d'
down_revision: Union[str, Sequence[str], None] = '096705cc8648'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('acceso', sa.Column('ip', sa.String(), nullable=True))
    op.add_column('acceso', sa.Column('token', sa.String(), nullable=True))
    op.add_column('acceso', sa.Column('activo', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('acceso', sa.Column('navegador_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_acceso_token'), 'acceso', ['token'], unique=False)
    op.create_foreign_key(
        'fk_acceso_navegador_id_navegador',
        'acceso',
        'navegador',
        ['navegador_id'],
        ['id']
    )
    op.alter_column('acceso', 'activo', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_acceso_navegador_id_navegador', 'acceso', type_='foreignkey')
    op.drop_index(op.f('ix_acceso_token'), table_name='acceso')
    op.drop_column('acceso', 'navegador_id')
    op.drop_column('acceso', 'activo')
    op.drop_column('acceso', 'token')
    op.drop_column('acceso', 'ip')
    # ### end Alembic commands ###
